drop table if exists books cascade;
drop table if exists readers cascade;
drop table if exists book_loans cascade;

create table books
(
    id               bigint generated by default as identity,
    book_name        varchar(100) not null,
    author           varchar(100) not null,
    isbn             varchar(13) not null unique,
    publication_year varchar(5) not null,
    total_copies     integer      not null,
    available_copies integer      not null,
    primary key (id),
    CONSTRAINT valid_isbn_length CHECK (
        length(isbn) IN (10, 13)
        )
);

create table readers
(
    id                bigint generated by default as identity,
    first_name        varchar(100) not null,
    last_name         varchar(100) not null,
    email             varchar(60) not null unique,
    phone_number      varchar(11) not null unique,
    registration_date date         not null,
    primary key (id)
);

create table book_loans
(
    id          bigint generated by default as identity,
    book_id     bigint not null,
    reader_id   bigint not null,
    loan_date   date   not null,
    due_date    date   not null,
    return_date date,
    status      enum ('ISSUED','OVERDUE','RETURNED') not null,
    primary key (id)
);
