{
 "title": "Business Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Количество ошибок по эндпоинтам",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (URI, method) (\n  CONTROLLER_METHOD_EXECUTION_TIME_seconds_count{requestStatus=\"failed\"}\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Среднее время обработки запросов",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by (URI, method) (\n  avg_over_time(CONTROLLER_METHOD_EXECUTION_TIME_seconds_sum[$__interval])\n  /\n  (avg_over_time(CONTROLLER_METHOD_EXECUTION_TIME_seconds_count[$__interval]) > 0)\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Количество зарегистрированных читателей",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    { "expr": "REGISTERED_READER_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Количество возвращенных книг",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    { "expr": "RETURNED_BOOK_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Количество выданных книг",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    { "expr": "ISSUED_BOOK_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Количество просроченных книг",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "targets": [
    { "expr": "OVERDUE_BOOK_total", "legendFormat": "__auto" }
   ]
  }
 ]
}